{% set name = "pyppeteer" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 153c62666fe1d55b3941d1634733c02cafb47188fcf282987371e863d58f22e9
  patches:
    - conda-forge.patch

build:
  noarch: python
  number: 0
  entry_points:
    - pyppeteer-install = pyppeteer.command:install
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - pyee
    - websockets
    - appdirs
    - urllib3
    - tqdm
    - certifi

test:
  imports:
    - pyppeteer

about:
  home: https://github.com/miyakogi/pyppeteer
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Headless chrome/chromium automation library (unofficial port of puppeteer)
  doc_url: https://miyakogi.github.io/pyppeteer
  dev_url: https://github.com/miyakogi/pyppeteer

extra:
  recipe-maintainers:
    - kiwi0fruit
